---

- hosts: all
  tasks:
    - name: install python packages using conda
      shell: "/usr/local/anaconda/bin/conda install -c conda-forge {{ item }}"
      with_items:
        - xgboost
        - folium
        - psycopg2
        - sqlalchemy
        - geopy
        - geojson
        - lightgbm
        - eli5
        - shap
        - catboost
        - mlxtend
        - pytorch
        - pandas==0.24.1
      environment:
        ANACONDA_DIR: /usr/local/anaconda
        PATH: "${ANACONDA_DIR}/bin:${PATH}"
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version|version_compare(16.04, '<=')
      changed_when: no
      tags:
        - skip_ansible_lint
