---

driver:
  name: docker

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  log: True
  playbooks:
    converge: ../../playbook.yml

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - destroy

platforms:
  - name: ubuntu
    image: ubuntu:16.04
